### ISSUE TITLE
run in local and not in HDFS

### ISSUE THREAD

**Issue by NinaSou** [digital-preservation/csv-validator#123]
I wanted to use this validator on a hadoop environment but it doesn't work because the reading is done on local file, how can I change this so it can read from HDFS please?

**Comment by adamretter** [comment]
It is possible to use a `java.io.Reader` as the input instead of a file path, see - https://github.com/digital-preservation/csv-validator/blob/master/csv-validator-core/src/main/scala/uk/gov/nationalarchives/csv/validator/api/CsvValidator.scala#L54

**Comment by NinaSou** [comment]
Thank you for the answer. Now I am having an other problem. When I run it on Hadoop I have these error :  java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon
After some research on the net it may th version of scala 2.11 that is used on the API tha cause the problem. Can you help with this issue too please? 
![error](https://cloud.githubusercontent.com/assets/19435802/15378889/ba11b832-1d67-11e6-829b-3798e2512404.PNG)

**Comment by adamretter** [comment]
The CSV Validator uses Scala 2.11.7, I think it would also compile on 2.11.8 and probably several earlier version of 2.11.

I suspect that you have a different scala-lang-*.jar on your classpath in Hadoop which is older (i.e. pre 2.11). Can you check your classpath please?

**Comment by NinaSou** [comment]
Acctually the hadoop use the scala version 2.10 and I can't modify it. I have take the version of the validator API 1.0-RC3 that use scala 2.10 and I had a different error. The error is like below 
![error validate](https://cloud.githubusercontent.com/assets/19435802/15396995/c139cf60-1dde-11e6-8691-aba55fbc6bba.PNG)

An other problem is with the schema CSV when I run it locally it put The error : ERROR:[2.1] failure : Invalid schema text. it seem's that The problem is with @separator '|' @quoted @totalColumns 20 @noHeader
When I use only the totalColumns and no Header it do the validation but with separator and quoted it fail.

Thank you for your help :)

**Comment by NinaSou** [comment]
I have search for some exemple for schema that we can use with version of the validator 1.0-RC3 but I didn't find that.
If you can provide me an exemple that use separator please? thank you

**Comment by DavidUnderdown** [comment]
I'm pretty sure 1.0 RC3 didn't support the separator directive fully (see #48, which post-dates RC3).  Any other aspects of CSV Schema Language 1.0 should be OK with RC3 in general terms but there have been various bug fixes and performance improvements since then.

**Comment by adamretter** [comment]
@NinaSou Please can you open a separate issue for your CSV Schema issue and remove the details of that from here? I don't want to mix the two issues!

I am afraid that I cannot support older versions of the CSV Validator, unfortunately I just don't have the resources. If you want to use an older version of the CSV Validator or an older version of Scala then I am afraid that you are mostly on your own. The CSV Validator uses libraries such as ScalaZ which are very much dependent on a specific major version of Scala.

AFAIK Hadoop itself does not have a dependency on Scala. Perhaps your dependency on Scala 2.10 is introduced by other Scala code that you have running in Hadoop? We have ourselves successfully used the CSV Validator inside our Hadoop MapReduce framework, however all of our code is Scala 2.11.
